template-file-path: ecs-cicd/templates/ecs-cicd.yaml
parameters:
  ProjectName: ecs-cicd-lab
  GitHubOrg: Grandkojo
  AppRepoName: ecs-cicd-app
  ContainerPort: '80'
  InitialImage: public.ecr.aws/docker/library/nginx:alpine
tags:
  Project: ecs-cicd-lab
