template-file-path: ecs-cicd/templates/ecs-cicd.yaml
parameters:
  GitHubOrg: Grandkojo
  AppRepoName: ecs-cicd-app
  ProjectName: ecs-cicd-lab-v2
tags:
  Project: ecs-cicd-lab
  Lab: ECS-CICD
  ManagedBy: CloudFormation-GitSync
